image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://localhost:2375

stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:19-dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t es-operator:${CI_PIPELINE_ID} .
    - docker tag es-operator:${CI_PIPELINE_ID} ${CI_REGISTRY}/mordor/es-operator:1.0.${CI_PIPELINE_ID}
    - docker push ${CI_REGISTRY}/mordor/es-operator:1.0.${CI_PIPELINE_ID}
  only:
    - master
  tags:
    - k8s
  allow_failure: false
